### ISSUE TITLE
ImportError: cannot import name '_C'

### ISSUE THREAD

**Issue by KelvinHuang666** [sfzhang15/ATSS#10]
Traceback (most recent call last):
  File "tools/train_net.py", line 15, in <module>
    from atss_core.data import make_data_loader
  File "/atss/ATSS/tools/atss_core/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/atss/ATSS/tools/atss_core/data/build.py", line 10, in <module>
    from . import datasets as D
  File "/atss/ATSS/tools/atss_core/data/datasets/__init__.py", line 2, in <module>
    from .coco import COCODataset
  File "/atss/ATSS/tools/atss_core/data/datasets/coco.py", line 6, in <module>
    from atss_core.structures.segmentation_mask import SegmentationMask
  File "/atss/ATSS/tools/atss_core/structures/segmentation_mask.py", line 5, in <module>
    from atss_core.layers.misc import interpolate
  File "/atss/ATSS/tools/atss_core/layers/__init__.py", line 10, in <module>
    from .nms import nms, ml_nms
  File "/atss/ATSS/tools/atss_core/layers/nms.py", line 3, in <module>
    from atss_core import _C
ImportError: cannot import name '_C'

**Comment by sfzhang15** [comment]
@KelvinHuang666 
Do you run the ''python setup.py build develop --no-deps'' ?

**Comment by sfzhang15** [comment]
I close this issue because there was no response for a long time, please reopen it if there are still problems.

**Comment by Adnan-annan** [comment]
if I run python setup.py build develop --no-deps, I get the error subprocess.CalledProcessError: Command '['xcrun', '-v']' returned non-zero exit status 64. can you help me how to solve this problem ?
I am running it on Mac OS

**Comment by sunnysky29** [comment]
WHY  your environment is so hard to run ??? @sfzhang15
