### ISSUE TITLE
ImportError: /root/atss/ATSS/atss_core/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by Note-Liu** [sfzhang15/ATSS#17]
(base) root@a096b2d397ad:~/atss/ATSS# python demo/atss_demo.py
Traceback (most recent call last):
  File "demo/atss_demo.py", line 6, in <module>
    from predictor import COCODemo
  File "/root/atss/ATSS/demo/predictor.py", line 6, in <module>
    from atss_core.modeling.detector import build_detection_model
  File "/root/atss/ATSS/atss_core/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/root/atss/ATSS/atss_core/modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/root/atss/ATSS/atss_core/modeling/detector/generalized_rcnn.py", line 11, in <module>
    from ..backbone import build_backbone
  File "/root/atss/ATSS/atss_core/modeling/backbone/__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "/root/atss/ATSS/atss_core/modeling/backbone/backbone.py", line 7, in <module>
    from atss_core.modeling.make_layers import conv_with_kaiming_uniform
  File "/root/atss/ATSS/atss_core/modeling/make_layers.py", line 10, in <module>
    from atss_core.layers import Conv2d
  File "/root/atss/ATSS/atss_core/layers/__init__.py", line 10, in <module>
    from .nms import nms, ml_nms
  File "/root/atss/ATSS/atss_core/layers/nms.py", line 3, in <module>
    from atss_core import _C
ImportError: /root/atss/ATSS/atss_core/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration

**Comment by sfzhang15** [comment]
@Note-Liu 
Please refer to [solution1](https://github.com/open-mmlab/mmdetection/issues/66), [solution2](https://github.com/rusty1s/pytorch_scatter/issues/19) and [solution3](https://www.cnblogs.com/luruiyuan/p/10720581.html)

**Comment by Note-Liu** [comment]
> @Note-Liu
> Please refer to solution1, solution2 and solution3

thanks
