### ISSUE TITLE
_c error

### ISSUE THREAD

**Issue by HansolEom** [sfzhang15/ATSS#18]
running build
running build_py
running egg_info
writing atss.egg-info/PKG-INFO
writing dependency_links to atss.egg-info/dependency_links.txt
writing requirements to atss.egg-info/requires.txt
writing top-level names to atss.egg-info/top_level.txt
reading manifest file 'atss.egg-info/SOURCES.txt'
writing manifest file 'atss.egg-info/SOURCES.txt'
running build_ext
running develop
running build_ext
copying build/lib.linux-x86_64-3.7/atss_core/_C.cpython-37m-x86_64-linux-gnu.so -> atss_core
Creating /home/hansol/anaconda3/envs/ATSS/lib/python3.7/site-packages/atss.egg-link (link to .)
atss 0.1 is already the active version in easy-install.pth

Traceback (most recent call last):
  File "tools/test_net.py", line 11, in <module>
    from atss_core.data import make_data_loader
  File "/home/hansol/PycharmProjects/ATSS/atss_core/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/home/hansol/PycharmProjects/ATSS/atss_core/data/build.py", line 10, in <module>
    from . import datasets as D
  File "/home/hansol/PycharmProjects/ATSS/atss_core/data/datasets/__init__.py", line 2, in <module>
    from .coco import COCODataset
  File "/home/hansol/PycharmProjects/ATSS/atss_core/data/datasets/coco.py", line 6, in <module>
    from atss_core.structures.segmentation_mask import SegmentationMask
  File "/home/hansol/PycharmProjects/ATSS/atss_core/structures/segmentation_mask.py", line 5, in <module>
    from atss_core.layers.misc import interpolate
  File "/home/hansol/PycharmProjects/ATSS/atss_core/layers/__init__.py", line 10, in <module>
    from .nms import nms, ml_nms
  File "/home/hansol/PycharmProjects/ATSS/atss_core/layers/nms.py", line 3, in <module>
    from atss_core import _C
ImportError: /home/hansol/PycharmProjects/ATSS/atss_core/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration

I built but there is a _C error.

**Comment by sfzhang15** [comment]
@HansolEom 
Please refer to [this issue](https://github.com/sfzhang15/ATSS/issues/17).

**Comment by sfzhang15** [comment]
I close this issue because there was no response for a long time, please reopen it if there are still problems.
