### ISSUE TITLE
No module named 'atss_core"

### ISSUE THREAD

**Issue by xafarranxera** [sfzhang15/ATSS#20]
Good morning,

When I try to run the demo, I get the following error:

```(ATSS) vortiz@vortiz-pc:~/ATSS$ python demo/atss_demo.py
Traceback (most recent call last):
  File "demo/atss_demo.py", line 5, in <module>
    from atss_core.config import cfg
ModuleNotFoundError: No module named 'atss_core'```

Does anyone know why?

**Comment by sfzhang15** [comment]
@xafarranxera 
It looks like the path problem, did you modify anything?

**Comment by xafarranxera** [comment]
Now I fixed it, but a major error is still present:

`(ATSS) vortiz@vortiz-pc:~/ATSS$ python demo/atss_demo.py
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/THC/THCGeneral.cpp line=51 error=30 : unknown error
Traceback (most recent call last):
  File "demo/atss_demo.py", line 114, in <module>
    main()
  File "demo/atss_demo.py", line 98, in main
    min_image_size=args.min_image_size
  File "/home/vortiz/ATSS/demo/predictor.py", line 112, in __init__
    self.model.to(self.device)
  File "/home/vortiz/anaconda3/envs/ATSS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/home/vortiz/anaconda3/envs/ATSS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/vortiz/anaconda3/envs/ATSS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/vortiz/anaconda3/envs/ATSS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/vortiz/anaconda3/envs/ATSS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/home/vortiz/anaconda3/envs/ATSS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/home/vortiz/anaconda3/envs/ATSS/lib/python3.7/site-packages/torch/cuda/__init__.py", line 163, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/THC/THCGeneral.cpp:51
`
So, do we COMPULSORY need a CUDA GPU to run the demo?

Thanks in advance.

**Comment by sfzhang15** [comment]
@xafarranxera 
During inference, [ml_nms](https://github.com/sfzhang15/ATSS/blob/master/atss_core/csrc/ml_nms.h) is used, which does not support CPU. You can use [nms](https://github.com/sfzhang15/ATSS/blob/master/atss_core/csrc/nms.h).

**Comment by xafarranxera** [comment]
Excuse me, but I'm not able to tell how the error presented above relates with nms...

**Comment by sfzhang15** [comment]
@xafarranxera 
From your error message, I do not know the reason behind it, you better debug to find the reason. The previous response is to your question that "do we COMPULSORILY need a CUDA GPU to run the demo?".
