### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Forgetmyfairy** [sfzhang15/ATSS#3]
A problem occurred while I run the test_net!

Traceback (most recent call last):
  File "/home/lab30202/sdb/liuqiang/2019-12-6-ATSS/ATSS-master/tools/test_net.py", line 100, in <module>
    main()
  File "/home/lab30202/sdb/liuqiang/2019-12-6-ATSS/ATSS-master/tools/test_net.py", line 64, in main
    model = build_detection_model(cfg)
  File "/home/lab30202/sdb/liuqiang/2019-12-6-ATSS/ATSS-master/atss_core/modeling/detector/detectors.py", line 10, in build_detection_model
    return meta_arch(cfg)
  File "/home/lab30202/sdb/liuqiang/2019-12-6-ATSS/ATSS-master/atss_core/modeling/detector/generalized_rcnn.py", line 31, in __init__
    self.roi_heads = build_roi_heads(cfg, self.backbone.out_channels)
  File "/home/lab30202/sdb/liuqiang/2019-12-6-ATSS/ATSS-master/atss_core/modeling/roi_heads/roi_heads.py", line 66, in build_roi_heads
    roi_heads.append(("box", build_roi_box_head(cfg, in_channels)))
  File "/home/lab30202/sdb/liuqiang/2019-12-6-ATSS/ATSS-master/atss_core/modeling/roi_heads/box_head/box_head.py", line 71, in build_roi_box_head
    return ROIBoxHead(cfg, in_channels)
  File "/home/lab30202/sdb/liuqiang/2019-12-6-ATSS/ATSS-master/atss_core/modeling/roi_heads/box_head/box_head.py", line 18, in __init__
    self.feature_extractor = make_roi_box_feature_extractor(cfg, in_channels)
  File "/home/lab30202/sdb/liuqiang/2019-12-6-ATSS/ATSS-master/atss_core/modeling/roi_heads/box_head/roi_box_feature_extractors.py", line 151, in make_roi_box_feature_extractor
    return func(cfg, in_channels)
  File "/home/lab30202/sdb/liuqiang/2019-12-6-ATSS/ATSS-master/atss_core/modeling/roi_heads/box_head/roi_box_feature_extractors.py", line 36, in __init__
    dilation=config.MODEL.RESNETS.RES5_DILATION
  File "/home/lab30202/sdb/liuqiang/2019-12-6-ATSS/ATSS-master/atss_core/modeling/backbone/resnet.py", line 194, in __init__
    dcn_config=dcn_config
  File "/home/lab30202/sdb/liuqiang/2019-12-6-ATSS/ATSS-master/atss_core/modeling/backbone/resnet.py", line 231, in _make_stage
    dcn_config=dcn_config
  File "/home/lab30202/sdb/liuqiang/2019-12-6-ATSS/ATSS-master/atss_core/modeling/backbone/resnet.py", line 390, in __init__
    dcn_config=dcn_config
  File "/home/lab30202/sdb/liuqiang/2019-12-6-ATSS/ATSS-master/atss_core/modeling/backbone/resnet.py", line 286, in __init__
    with_dcn = dcn_config.get("stage_with_dcn", False)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by sfzhang15** [comment]
@Forgetmyfairy 
Did you run with two-stage detectors?

**Comment by Forgetmyfairy** [comment]
@sfzhang15  I just follow your Readme.md and run “python3 tools/test_net.py” ，do I need to do anything else?

**Comment by sfzhang15** [comment]
@Forgetmyfairy 
Did you run as: `python tools/test_net.py --config-file configs/atss/atss_R_50_FPN_1x.yaml MODEL.WEIGHT ATSS_R_50_FPN_1x.pth TEST.IMS_PER_BATCH 4 `?

**Comment by Forgetmyfairy** [comment]
Use Pycharm ide to run instead of Terminal...

**Comment by sfzhang15** [comment]
@Forgetmyfairy 
Input `--config-file configs/atss/atss_R_50_FPN_1x.yaml MODEL.WEIGHT ATSS_R_50_FPN_1x.pth TEST.IMS_PER_BATCH 4` to configurations as Parameters.

**Comment by Forgetmyfairy** [comment]
Wow, Thank you, It worked  well in your way.
