### ISSUE TITLE
ImportError: cannot import name '_C' from 'atss_core' 

### ISSUE THREAD

**Issue by Huanqing1** [sfzhang15/ATSS#40]
/opt/Anaconda3/envs/ATSS_cuda10/bin/python3.7 /home/data/zhanghuanqing/ATSS/ATSS_HRRSD_origin/ATSS-master/tools/test_net.py
Traceback (most recent call last):
  File "/home/data/zhanghuanqing/ATSS/ATSS_HRRSD_origin/ATSS-master/tools/test_net.py", line 11, in <module>
    from atss_core.data import make_data_loader
  File "/home/data/zhanghuanqing/ATSS/ATSS_HRRSD_origin/ATSS-master/atss_core/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/home/data/zhanghuanqing/ATSS/ATSS_HRRSD_origin/ATSS-master/atss_core/data/build.py", line 10, in <module>
    from . import datasets as D
  File "/home/data/zhanghuanqing/ATSS/ATSS_HRRSD_origin/ATSS-master/atss_core/data/datasets/__init__.py", line 2, in <module>
    from .coco import COCODataset
  File "/home/data/zhanghuanqing/ATSS/ATSS_HRRSD_origin/ATSS-master/atss_core/data/datasets/coco.py", line 6, in <module>
    from atss_core.structures.segmentation_mask import SegmentationMask
  File "/home/data/zhanghuanqing/ATSS/ATSS_HRRSD_origin/ATSS-master/atss_core/structures/segmentation_mask.py", line 5, in <module>
    from atss_core.layers.misc import interpolate
  File "/home/data/zhanghuanqing/ATSS/ATSS_HRRSD_origin/ATSS-master/atss_core/layers/__init__.py", line 10, in <module>
    from .nms import nms, ml_nms
  File "/home/data/zhanghuanqing/ATSS/ATSS_HRRSD_origin/ATSS-master/atss_core/layers/nms.py", line 3, in <module>
    from atss_core import _C
ImportError: cannot import name '_C' from 'atss_core' (/home/data/zhanghuanqing/ATSS/ATSS_HRRSD_origin/ATSS-master/atss_core/__init__.py)

**Comment by Huanqing1** [comment]
When I run test_net.py in pycharm, I get this error. But I can run in command prompt.

**Comment by Huanqing1** [comment]
Maybe I find the source of the error, but I still can not solve it.
I use Python3.7,the file seems to be python3.6: _C.cpython-36m-x86_64-linux-gnu.so 
Anyone can help me?

**Comment by Huanqing1** [comment]
I soved.

**Comment by coolbay** [comment]
@Huanqing1 I ran into the same error. How did you solve it?

**Comment by coolbay** [comment]
@Huanqing1 I solved it based on your description of the error source. It is because python version mismatch.  Once I change my python version to the same as the ` _C.cpython-36m-x86_64-linux-gnu.so` file, and recompile `python setup.py build develop --no-deps`. I suggest the authors specify the python version used in this repo so that future users wouldn't get into the same trouble. @sfzhang15 

Thank you very much!

**Comment by sfzhang15** [comment]
@coolbay 
OK, thanks for your suggestion.
