### ISSUE TITLE
python setup.py build develop --no-deps, 

### ISSUE THREAD

**Issue by Adnan-annan** [sfzhang15/ATSS#63]
if I run python setup.py build develop --no-deps, I get the error subprocess.CalledProcessError: Command '['xcrun', '-v']' returned non-zero exit status 64. can you help me how to solve this problem ?
I am running it on Mac OS

Traceback (most recent call last):
  File "setup.py", line 76, in <module>
    include_package_data=True,
  File "/Users/adnan/Desktop/ATSS/atss/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/adnan/Desktop/ATSS/atss/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/Users/adnan/Desktop/ATSS/atss/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/Users/adnan/Desktop/ATSS/atss/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 344, in build_extensions
    self._check_abi()
  File "/Users/adnan/Desktop/ATSS/atss/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 675, in _check_abi
    check_compiler_abi_compatibility(compiler)
  File "/Users/adnan/Desktop/ATSS/atss/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 248, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/Users/adnan/Desktop/ATSS/atss/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 215, in check_compiler_ok_for_platform
    version_string = subprocess.check_output([compiler, '-v'], stderr=subprocess.STDOUT).decode()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['xcrun', '-v']' returned non-zero exit status 64.

**Comment by sfzhang15** [comment]
@Adnan-annan 
From these error information, I do not know how to solve it. For specific compilation problems, please try to find solutions online.
